#!/usr/bin/expect -f
# $1 is a Bluetooth MAC address.
# example usage: bluetooth_connect.sh 08:EB:ED:F6:53:A3

set address [lindex $argv 0]

spawn bluetoothctl -a
expect -re "Agent registered"

send "power on\r"
expect -re "Changing power on succeeded"

send "trust $address\r"
expect -re "Changing $address trust succeeded"

send "connect $address\r"
expect -re "Connection successful"

send "quit\r"
expect -re "Agent unregistered"

expect eof
